# Generated by Django 5.1.4 on 2024-12-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
